# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-22 23:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CountryCultural',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.CharField(max_length=50, verbose_name='\u8be6\u60c5')),
                ('city', models.CharField(max_length=10, verbose_name='\u57ce\u5e02')),
                ('href', models.CharField(max_length=100, verbose_name='\u94fe\u63a5')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
                ('image', models.ImageField(upload_to='images/%Y/%m', verbose_name='\u6587\u5316\u56fe\u7247')),
                ('name', models.CharField(max_length=20, verbose_name='\u6587\u5316\u540d')),
            ],
            options={
                'verbose_name': '\u4e61\u6751\u6587\u5316',
                'verbose_name_plural': '\u4e61\u6751\u6587\u5316',
            },
        ),
        migrations.CreateModel(
            name='CountryFoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.CharField(max_length=50, verbose_name='\u8be6\u60c5')),
                ('city', models.CharField(max_length=10, verbose_name='\u57ce\u5e02')),
                ('href', models.CharField(max_length=100, verbose_name='\u94fe\u63a5')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
                ('image', models.ImageField(upload_to='images/%Y/%m', verbose_name='\u7f8e\u98df\u56fe\u7247')),
                ('name', models.CharField(max_length=20, verbose_name='\u7f8e\u98df\u540d')),
            ],
            options={
                'verbose_name': '\u4e61\u6751\u7f8e\u98df',
                'verbose_name_plural': '\u4e61\u6751\u7f8e\u98df',
            },
        ),
        migrations.CreateModel(
            name='CountryNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='\u4e61\u6751\u65b0\u95fb\u6807\u9898')),
                ('href', models.CharField(max_length=100, verbose_name='\u94fe\u63a5')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u4e61\u6751\u65b0\u95fb',
                'verbose_name_plural': '\u4e61\u6751\u65b0\u95fb',
            },
        ),
        migrations.CreateModel(
            name='CountryScince',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.CharField(max_length=50, verbose_name='\u8be6\u60c5')),
                ('city', models.CharField(max_length=10, verbose_name='\u57ce\u5e02')),
                ('href', models.CharField(max_length=100, verbose_name='\u94fe\u63a5')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
                ('image', models.ImageField(upload_to='images/%Y/%m', verbose_name='\u666f\u8272\u56fe\u7247')),
                ('name', models.CharField(max_length=20, verbose_name='\u666f\u8272\u540d')),
            ],
            options={
                'verbose_name': '\u4e61\u6751\u666f\u8272',
                'verbose_name_plural': '\u4e61\u6751\u666f\u8272',
            },
        ),
        migrations.CreateModel(
            name='CountryTourist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.CharField(max_length=50, verbose_name='\u8be6\u60c5')),
                ('city', models.CharField(max_length=10, verbose_name='\u57ce\u5e02')),
                ('href', models.CharField(max_length=100, verbose_name='\u94fe\u63a5')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
                ('image', models.ImageField(upload_to='images/%Y/%m', verbose_name='\u65c5\u6e38\u666f\u8272\u56fe\u7247')),
                ('name', models.CharField(max_length=20, verbose_name='\u65c5\u6e38\u666f\u8272\u540d')),
                ('season', models.CharField(max_length=6, verbose_name='\u5b63\u8282')),
                ('rank', models.CharField(max_length=2, verbose_name='\u7b49\u7ea7')),
                ('price', models.IntegerField(default=0, verbose_name='\u4ef7\u683c')),
                ('person', models.IntegerField(default=0, verbose_name='\u4eba\u6c14')),
            ],
            options={
                'verbose_name': '\u4e61\u6751\u65c5\u6e38',
                'verbose_name_plural': '\u4e61\u6751\u65c5\u6e38',
            },
        ),
    ]
