# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-23 13:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Country', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countrycultural',
            name='image',
            field=models.CharField(max_length=100, verbose_name='\u6587\u5316\u56fe\u7247'),
        ),
        migrations.AlterField(
            model_name='countryfoods',
            name='image',
            field=models.CharField(max_length=100, verbose_name='\u7f8e\u98df\u56fe\u7247'),
        ),
        migrations.AlterField(
            model_name='countryscince',
            name='image',
            field=models.CharField(max_length=100, verbose_name='\u666f\u8272\u56fe\u7247'),
        ),
        migrations.AlterField(
            model_name='countrytourist',
            name='image',
            field=models.CharField(max_length=100, verbose_name='\u65c5\u6e38\u666f\u8272\u56fe\u7247'),
        ),
    ]
