# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-24 17:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Country', '0003_auto_20170524_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countrycultural',
            name='detail',
            field=models.CharField(max_length=300, verbose_name='\u8be6\u60c5'),
        ),
        migrations.AlterField(
            model_name='countrycultural',
            name='href',
            field=models.CharField(max_length=300, verbose_name='\u94fe\u63a5'),
        ),
        migrations.AlterField(
            model_name='countryfoods',
            name='detail',
            field=models.CharField(max_length=300, verbose_name='\u8be6\u60c5'),
        ),
        migrations.AlterField(
            model_name='countryfoods',
            name='href',
            field=models.CharField(max_length=300, verbose_name='\u94fe\u63a5'),
        ),
        migrations.AlterField(
            model_name='countrynews',
            name='href',
            field=models.CharField(max_length=300, verbose_name='\u94fe\u63a5'),
        ),
        migrations.AlterField(
            model_name='countryscince',
            name='detail',
            field=models.CharField(max_length=300, verbose_name='\u8be6\u60c5'),
        ),
        migrations.AlterField(
            model_name='countryscince',
            name='href',
            field=models.CharField(max_length=300, verbose_name='\u94fe\u63a5'),
        ),
        migrations.AlterField(
            model_name='countrytourist',
            name='detail',
            field=models.CharField(max_length=300, verbose_name='\u8be6\u60c5'),
        ),
        migrations.AlterField(
            model_name='countrytourist',
            name='href',
            field=models.CharField(max_length=300, verbose_name='\u94fe\u63a5'),
        ),
    ]
