# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-24 17:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Country', '0004_auto_20170524_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='countryscince',
            name='mark',
            field=models.CharField(default='F', max_length=1, verbose_name='\u4e61\u6751\u6807\u8bb0'),
        ),
    ]
