# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-24 18:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Country', '0006_auto_20170524_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countrycultural',
            name='image',
            field=models.ImageField(default='/static/images/default.jpg', upload_to='static/images/%Y/%m', verbose_name='\u6587\u5316\u56fe\u7247'),
        ),
        migrations.AlterField(
            model_name='countryfoods',
            name='image',
            field=models.ImageField(default='/static/images/default.jpg', upload_to='static/images/%Y/%m', verbose_name='\u7f8e\u98df\u56fe\u7247'),
        ),
        migrations.AlterField(
            model_name='countryscince',
            name='image',
            field=models.ImageField(default='/static/images/default.jpg', upload_to='static/images/%Y/%m', verbose_name='\u666f\u8272\u56fe\u7247'),
        ),
        migrations.AlterField(
            model_name='countrytourist',
            name='image',
            field=models.ImageField(default='/static/images/default.jpg', upload_to='static/images/%Y/%m', verbose_name='\u65c5\u6e38\u666f\u8272\u56fe\u7247'),
        ),
    ]
