# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-26 18:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Country', '0007_auto_20170524_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='countrycultural',
            name='phone',
            field=models.CharField(default='0598-7833822', max_length=11, verbose_name='\u7535\u8bdd'),
        ),
        migrations.AddField(
            model_name='countryfoods',
            name='phone',
            field=models.CharField(default='0598-7833822', max_length=11, verbose_name='\u7535\u8bdd'),
        ),
        migrations.AddField(
            model_name='countryscince',
            name='phone',
            field=models.CharField(default='0598-7833822', max_length=11, verbose_name='\u7535\u8bdd'),
        ),
        migrations.AddField(
            model_name='countrytourist',
            name='kinds_of_tourist',
            field=models.CharField(default='\u5c71\u5cf0', max_length=10, verbose_name='\u666f\u70b9\u7c7b\u578b'),
        ),
        migrations.AddField(
            model_name='countrytourist',
            name='phone',
            field=models.CharField(default='0598-7833822', max_length=11, verbose_name='\u7535\u8bdd'),
        ),
    ]
