# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-26 19:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Country', '0008_auto_20170526_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='countryfoods',
            name='price',
            field=models.CharField(default='30', max_length=20, verbose_name='\u4ef7\u683c'),
        ),
    ]
