# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-26 19:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Country', '0009_countryfoods_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='countrytourist',
            name='open_time',
            field=models.CharField(default='\u590f\u5b63\uff1a07:30~15:30 \u51ac\u5b63\uff1a07:30~15:00', max_length=100, verbose_name='\u5f00\u653e\u65f6\u95f4'),
        ),
    ]
