# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-26 19:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Country', '0010_countrytourist_open_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='countrytourist',
            name='kinds_of_tourist',
        ),
        migrations.AddField(
            model_name='countrycultural',
            name='kinds_of',
            field=models.CharField(default='\u4e61\u6751\u6587\u5316', max_length=10, verbose_name='\u7c7b\u578b'),
        ),
        migrations.AddField(
            model_name='countryfoods',
            name='kinds_of',
            field=models.CharField(default='\u7f8e\u98df', max_length=10, verbose_name='\u7c7b\u578b'),
        ),
        migrations.AddField(
            model_name='countryscince',
            name='kinds_of',
            field=models.CharField(default='\u4e61\u6751\u98ce\u666f', max_length=10, verbose_name='\u7c7b\u578b'),
        ),
        migrations.AddField(
            model_name='countrytourist',
            name='kinds_of',
            field=models.CharField(default='\u5c71\u5cf0', max_length=10, verbose_name='\u666f\u70b9\u7c7b\u578b'),
        ),
    ]
