# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-26 22:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Country', '0011_auto_20170526_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countrycultural',
            name='phone',
            field=models.CharField(default='0598-7833822', max_length=12, verbose_name='\u7535\u8bdd'),
        ),
        migrations.AlterField(
            model_name='countryfoods',
            name='phone',
            field=models.CharField(default='0598-7833822', max_length=12, verbose_name='\u7535\u8bdd'),
        ),
        migrations.AlterField(
            model_name='countryscince',
            name='phone',
            field=models.CharField(default='0598-7833822', max_length=12, verbose_name='\u7535\u8bdd'),
        ),
        migrations.AlterField(
            model_name='countrytourist',
            name='phone',
            field=models.CharField(default='0598-7833822', max_length=12, verbose_name='\u7535\u8bdd'),
        ),
    ]
