# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-24 17:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_auto_20170524_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='/static/images/default.jpg', upload_to='images/%Y/%m'),
        ),
    ]
