# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-24 21:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_auto_20170524_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='img',
            field=models.ImageField(upload_to='static/images/banner/%Y/%m', verbose_name='\u8f6e\u64ad\u56fe'),
        ),
    ]
