# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-27 23:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_auto_20170524_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='static/images/default.jpg', upload_to='static/images/%Y/%m'),
        ),
    ]
