# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-27 23:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0007_auto_20170527_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='sex',
            field=models.CharField(choices=[('male', '\u7537'), ('female', '\u5973')], default='\u7537', max_length=6),
        ),
    ]
